package com.understand_your_electricity_bill.dto;

import jakarta.validation.constraints.*;

/**
 * DTO for creating a new Consultant.
 * Does not include ID (generated by system) or calculated fields (like registrationDate).
 * Password will be hashed by the service layer.
 */
public record ConsultantCreateDTO(
        @NotBlank(message = "Email is required")
        @Email(message = "Email must be valid")
        @Pattern(regexp = "^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$",
                message = "Email format is invalid")
        String email,

        @NotBlank(message = "Password is required")
        @Size(min = 8, max = 100, message = "Password must be between 8 and 100 characters")
        @Pattern(regexp = "^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,}$",
                message = "Password must contain at least one uppercase letter, one lowercase letter, one number and one special character")
        String password,

        @NotBlank(message = "Name is required")
        @Size(max = 255, message = "Name must not exceed 255 characters")
        String name,

        @Pattern(regexp = "^\\+?[0-9]{10,15}$",
                message = "Phone must contain 10-15 digits and may start with +")
        String phone,

        @NotBlank(message = "Consultant name is required")
        @Size(max = 255, message = "Consultant name must not exceed 255 characters")
        String consultantName,

        @NotBlank(message = "Company is required")
        @Size(max = 255, message = "Company name must not exceed 255 characters")
        String company,

        @NotBlank(message = "CNPJ is required")
        @Pattern(regexp = "^\\d{14}$", message = "CNPJ must contain exactly 14 digits")
        String cnpj,

        @Size(max = 50, message = "Registration number must not exceed 50 characters")
        String registrationNumber,

        @NotBlank(message = "Address is required")
        @Size(max = 500, message = "Address must not exceed 500 characters")
        String address,

        @Size(max = 100, message = "City must not exceed 100 characters")
        String city,

        @Size(max = 2, message = "State must be 2 characters (e.g., SP)")
        @Pattern(regexp = "^[A-Z]{2}$", message = "State must be 2 uppercase letters")
        String state,

        @Pattern(regexp = "^\\d{5}-?\\d{3}$", message = "ZIP code must be in format 12345-678 or 12345678")
        String zipCode,

        String companyLogo
) {
    /**
     * Compact constructor with validation and normalization
     */
    public ConsultantCreateDTO {
        // Trim and normalize strings
        if (email != null) email = email.trim().toLowerCase();
        if (name != null) name = name.trim();
        if (consultantName != null) consultantName = consultantName.trim();
        if (company != null) company = company.trim();
        if (cnpj != null) cnpj = cnpj.replaceAll("[^0-9]", ""); // Remove non-digits
        if (registrationNumber != null) registrationNumber = registrationNumber.trim();
        if (phone != null) phone = phone.trim();
        if (address != null) address = address.trim();
        if (city != null) city = city.trim();
        if (state != null) state = state.trim().toUpperCase();
        if (zipCode != null) zipCode = zipCode.replaceAll("[^0-9]", ""); // Remove dashes
        if (companyLogo != null) companyLogo = companyLogo.trim();
    }
}

